# Generated by Django 3.2.9 on 2021-12-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=2700)),
                ('age', models.TextField(max_length=2700)),
            ],
        ),
    ]
