# Generated by Django 3.2.9 on 2021-12-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=2700)),
                ('age', models.TextField(max_length=2700)),
            ],
        ),
    ]
