# Generated by Django 3.2.9 on 2021-12-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fault',
            field=models.TextField(default=None),
        ),
    ]
